name: TypeScript

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript files
        run: npm run build
